### ISSUE TITLE
return statement needed when chaining in match function

### ISSUE THREAD

**Issue by sjorsengels** [dlo9/with#1]
In the following code the return statement in de lets function is needed for a correct built. Following the documentation, this should not be needed.
`fn get_available_ports() -> Response {
        match serialport::available_ports() {
            Ok(ports) => 
                 ports
                    .iter()
                    .map(|port| port.port_name.to_owned())
                    .collect::<Vec<String>>()
                    .lets(|it| {
                        println!("Found {} ports", it.len());
                        return Response::json(&[it]);
                    }).lets(|it| {
                        println!("Should be printed as well");
                        return it;
                    }) ,
            Err(_) => 
                 Response::empty_404()
        }
    }`

**Comment by hannesbraun** [comment]
`return` actually isn't needed. The following code should be equivalent:

```rust
fn get_available_ports() -> Response {
    match serialport::available_ports() {
        Ok(ports) => ports.iter().map(|port| port.port_name.to_owned()).collect::<Vec<String>>().lets(|it| {
            println!("Found {} ports", it.len());
            Response::json(&[it])
        }).lets(|it| {
            println!("Should be printed as well");
            it
        }),
        Err(_) => Response::empty_404()
    }
}
```

Note the absence of the semicolon at the last expressions in the let blocks.
